Creación del endpoint del estado del agente
TC3005B-562-2024/Spring-Boot-Backend pull request #15
Opened 2024-04-07 22:22 UTC by FranciscoSanchezz

Se creó el endpoint que regresa el estado de los agentes. Y el controlador de dicho endpoint (quería ver si si está bien como lo plantee porque creo que a como lo hice todos los endpoints que usen el método GET podrían agruparse en el controlador que puse)

2024-04-07 22:31 UTC, Djmr5 requested changes
Creo que sería mejor si lo pones en el controller de AgentController, y así separamos cada enpoint no por método de GET, POST, etc. Pero los dividimos por objeti tipo: agents, alerts, etc.

Yo diría que checaras el AgentController y pusieras ahí el método, igual puedes cheacar el Instance controller por si te sirve, y creo que alguien ya se adelanto pero te dejo un AgentDTO en una carpeta dentro de los DTOs

[AgentDTO en main](https://github.com/TC3005B-562-2024/Spring-Boot-Backend/blob/main/src/main/java/tc3005b224/amazonconnectinsights/dto/agent/AgentDTO.java)
[Agent Controller en main](https://github.com/TC3005B-562-2024/Spring-Boot-Backend/blob/main/src/main/java/tc3005b224/amazonconnectinsights/controllers/AgentController.java)

Ejemplo de un GetRequest sin modificar el RequestMapping:

```java
@GetMapping({ "/", "" })
    public ResponseEntity<InstanceDTO> getInstanceData() {}
```

2024-04-07 22:52 UTC, FranciscoSanchezz commented
Va ahora lo cambio

2024-04-08 00:09 UTC, FranciscoSanchezz commented
Ya quedó

2024-04-08 00:11 UTC, Djmr5 submitted a review, later dismissed
Excelente, le hago merge

2024-04-08 00:38 UTC, Djmr5 approved these changes

2024-04-08 00:38 UTC, merged