Estructura base del endpoint funcionando
TC3005B-562-2024/Spring-Boot-Backend pull request #16
Opened 2024-04-07 22:33 UTC by JourneyHM

2024-04-07 23:12 UTC, Djmr5 requested changes
Se ve bien, aunque crees que puedas poner el endpoint dentro del AgentController?

También si puedes poner el **agent_id** y el **call_id** como parametro?
/agents/{agent_id}/calls/{call_id}

Un ejemplo de como hacer esto sería:
```java
@GetMapping("/{agentId}/calls/{callId}")
    public ResponseEntity<List<InfoCallsDTO>> getCallInfo(@PathVariable("agentId") int agentId, @PathVariable("callId") int callId) {
        List<InfoCallsDTO> result = new ArrayList<>();
        InfoCallsDTO call1 = new InfoCallsDTO();
        call1.setClient_id(callId);
        call1.setDate("2024-04-07 15:30:00");
        call1.setCall_duration("01:30:15");
        List<EmotionDTO> emotionsdetected = new ArrayList<>();
        EmotionDTO e1 = new EmotionDTO();
        e1.setEmotion("angry");
        e1.setTime("00:50:00");
        emotionsdetected.add(e1);
        call1.setEmotions_detected(emotionsdetected);
        result.add(call1);
        return ResponseEntity.ok(result);
    }
```

2024-04-08 00:04 UTC, JourneyHM commented
Acabo de hacer un nuevo commit con los cambios propuestos.

2024-04-08 00:10 UTC, Djmr5 submitted a review, later dismissed
Maravilloso, le hago merge

2024-04-08 00:16 UTC, Djmr5 approved these changes

2024-04-08 00:17 UTC, merged