A01661896/instance skills
TC3005B-562-2024/Spring-Boot-Backend pull request #63
Opened 2024-04-10 01:35 UTC by Carl-MM

2024-04-10 17:34 UTC, Djmr5 requested changes

2024-04-10 17:34 UTC, Djmr5 commented on src/main/java/tc3005b224/amazonconnectinsights/controllers/SkillsController.java
> +                    @Content(mediaType = "application/json", schema = @Schema(implementation = InstanceDTO.class))
Creo que esto no debería ir así jajaja, podrías crear otro DTO que sea ListSkillDTO que tenga solo un atributo. Porque así parece que lo que va a regresar es un InstanceDTO

```java
public class ListSkillDTO {
    private List<SkillDTO> skills;
}
```

2024-04-10 17:34 UTC, Djmr5 commented on src/main/java/tc3005b224/amazonconnectinsights/controllers/SkillsController.java
> +        return null;
Xd está bien que regrese null?

2024-04-10 17:34 UTC, Djmr5 commented on src/main/java/tc3005b224/amazonconnectinsights/controllers/SkillsController.java
> +
Faltan los decoradores de OpenAPI

2024-04-10 22:54 UTC, Carl-MM commented on src/main/java/tc3005b224/amazonconnectinsights/controllers/SkillsController.java
> +        return null;
jony lo modificara, solo le puse la base

2024-04-11 01:59 UTC, Djmr5 approved these changes

2024-04-11 01:59 UTC, merged