Insights endpoints
TC3005B-562-2024/Spring-Boot-Backend pull request #97
Opened 2024-04-26 01:55 UTC by Carl-MM

2024-04-26 01:57 UTC, Carl-MM commented
#68

2024-04-28 22:56 UTC, Djmr5 requested changes

2024-04-28 22:56 UTC, Djmr5 commented on src/main/java/tc3005b224/amazonconnectinsights/models_sql/Insight.java
>  }
Implementar, podemos utilizar algo como model Mapper o borrarlo

2024-04-29 04:15 UTC, MoisesAdame approved these changes

2024-04-29 19:00 UTC, MoisesAdame approved these changes

2024-04-29 19:01 UTC, merged